[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
loyalty = "HWvvvwSEounpNXcbD4JUNmniB5YxTcFNYoAestzJJCuL"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
